language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
    - autopoint
    - gettext

install:
  #- apt install -y autoconf autopoint libtool pkg-config python-pip
  - pip install pathlib --user
  ->
    cat <<EOF > /etc/apt/sources.list.d/xenial.list
    deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ xenial universe
    deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ xenial main restricted
    deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ xenial-updates main restricted universe multiverse
    deb [arch=armhf,arm64] http://ports.ubuntu.com/ubuntu-ports/ xenial-backports main restricted universe multiverse

    deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ xenial universe
    deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ xenial main restricted
    deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ xenial-updates main restricted universe multiverse
    deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ xenial-backports main restricted universe multiverse
    EOF
  - dpkg --add-architecture armhf
  - apt-get update
  - apt-get install -y gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf g++-arm-linux-gnueabihf crossbuild-essential-armhf
  - apt-get install -y libpython2.7-dev:armhf

jobs:
  include:
    - stage: build
      script: |
              cd urjtag
              sed --in-place -e '/GETTEXT_VERSION/s/0.19/0.18/' configure.ac
              ./autogen.sh
              make -j$(nproc)
      script: |
              cd urjtag
              export CC=arm-linux-gnueabihf-gcc
              export LDSHARED="arm-linux-gnueabihf-gcc -L/usr/lib/arm-linux-gnueabihf -lpython2.7"
              CPP=arm-linux-gnueabihf-cpp ./autogen.sh --host=arm-linux
              make -j$(nproc)

deploy:
  provider: releases
  api_key:
    secure: qHljlP/0L/pWj0FVCGJ4auL9go3moYC6UuebmUdoWFtC2jMj5hEHTzydmHoEW+ZxTY3AF82KYdQva4RshmweX5PSx/HSY/GFxaCAlYTJqgHVZpXj5tzfT7POzjLqa84WYaF0kz8c9A/EvKBSsp5C9AyYkh2qkA1KImbqBHOfB3e3aOwvmDfoUV2CmlfSfHFgzXFf2lmmUV9aIE8zsKnmGjTy2qP+QtGDxq3UnMekeqHF+ga53NQSURzqU9cSd6CDl9XX2et0rowCylRKSNfqmejfYVm5rT3bK7pPQv4mxO/Yrwe1FBLJX0uRfxZomkd2Dikx9M55nlNY22jRNvtLzgWv9r3LnHM2um5RFG0oh9q3ybm2Scca6MQHU0K+s5JKlNcIqc6PKKw1lMlGB/7Yd9gEXyAFWQT9JqnWo3S7CJxFNQYtbCEHg4p35lVdlrDX2UWU7YKidbSl/iC00JeMKpvUycM03Je4epHVntHfb9cWM6/fY3x3hpY/hD00KuG+Faq//dy7CkThqdY6r3AmEfW8AI5GuBLKk/s0pHatE7tPeQJxmTjbGOVo2flHsyt9aNPW1ReYk19bGNUHNZtRN/7TsiqREXTtAoXDTaGOSmi6WmF+MIezFvaPqrXKulqJkyXWv+790cJGuy2EE1hiF1kGuPoLenX5TxgOHPGD8kw=
  file: ./urjtag/bindings/python/build/lib.linux-x86_64-2.7/urjtag.so
  on:
    repo: imsarllc/urjtag
    branch: deploy-artifacts
