#
# .travis.yml
# https://travis-ci.com/plans
#

language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
    - autopoint
    - gettext

install:
  - pip install pathlib --user

script: |
        cd urjtag 
        sed --in-place -e '/GETTEXT_VERSION/s/0.19/0.18/' configure.ac
        ./autogen.sh
        make

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: ./urjtag/bindings/python/build/lib.linux-x86_64-2.7/urjtag.so
  edge: true # dpl v2
  on:
    all_branches: true
    tags: false

# l l
