language: c

sudo: false

compiler:
  - gcc

addons:
  apt:
    packages:
    - autopoint
    - gettext

install:
  #- apt install -y autoconf autopoint libtool pkg-config python-pip # for testing w/ docker container
  - sudo rm -f /etc/apt/sources.list /etc/apt/sources.list.d/*
  - cat .ci/xenial.list | sudo tee /etc/apt/sources.list.d/xenial.list
  - sudo dpkg --add-architecture armhf
  - sudo apt-get update -yq
  - sudo apt-get install -yq gcc-arm-linux-gnueabihf binutils-arm-linux-gnueabihf g++-arm-linux-gnueabihf crossbuild-essential-armhf
  - sudo apt-get install -yq python3.5-dev:armhf python3.5-dev

jobs:
  include:
    - stage: build
      script: |
              cd urjtag
              sed --in-place -e '/GETTEXT_VERSION/s/0.19/0.18/' configure.ac
              ./autogen.sh
              make -j$(nproc)
      script: |
              cd urjtag
              # exports needed for setup.py
              export CC=arm-linux-gnueabihf-gcc
              export LDSHARED=arm-linux-gnueabihf-gcc
              CPP=arm-linux-gnueabihf-cpp PYTHON=/usr/bin/python3.5 ./autogen.sh --host=arm-linux --build=armv7l
              make -j$(nproc)

deploy:
  provider: releases
  api_key:
    secure: qHljlP/0L/pWj0FVCGJ4auL9go3moYC6UuebmUdoWFtC2jMj5hEHTzydmHoEW+ZxTY3AF82KYdQva4RshmweX5PSx/HSY/GFxaCAlYTJqgHVZpXj5tzfT7POzjLqa84WYaF0kz8c9A/EvKBSsp5C9AyYkh2qkA1KImbqBHOfB3e3aOwvmDfoUV2CmlfSfHFgzXFf2lmmUV9aIE8zsKnmGjTy2qP+QtGDxq3UnMekeqHF+ga53NQSURzqU9cSd6CDl9XX2et0rowCylRKSNfqmejfYVm5rT3bK7pPQv4mxO/Yrwe1FBLJX0uRfxZomkd2Dikx9M55nlNY22jRNvtLzgWv9r3LnHM2um5RFG0oh9q3ybm2Scca6MQHU0K+s5JKlNcIqc6PKKw1lMlGB/7Yd9gEXyAFWQT9JqnWo3S7CJxFNQYtbCEHg4p35lVdlrDX2UWU7YKidbSl/iC00JeMKpvUycM03Je4epHVntHfb9cWM6/fY3x3hpY/hD00KuG+Faq//dy7CkThqdY6r3AmEfW8AI5GuBLKk/s0pHatE7tPeQJxmTjbGOVo2flHsyt9aNPW1ReYk19bGNUHNZtRN/7TsiqREXTtAoXDTaGOSmi6WmF+MIezFvaPqrXKulqJkyXWv+790cJGuy2EE1hiF1kGuPoLenX5TxgOHPGD8kw=
  file: ./urjtag/bindings/python/build/lib.linux-x86_64-2.7/urjtag.so
  on:
    repo: imsarllc/urjtag
    branch: deploy-artifacts
